{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedRecordDot #-}

module Matrix where

data Three = Zero | One | Two
  deriving (Eq, Show)

flipThree :: Three -> Three
flipThree Zero = Two
flipThree One = One
flipThree Two = Zero

type Thrice a = Three -> a

thriceToTriple :: Thrice a -> (a, a, a)
thriceToTriple t = (t Zero, t One, t Two)

thrice :: a -> a -> a -> Thrice a
thrice x y z t =
  case t of
    Zero -> x
    One -> y
    Two -> z

-- | Note that there are two ways to access this field:
-- either with the
-- @get :: Matrix a -> Thrice (Thrice a)@
-- function which is autogenerated (not recommended)
-- or by using record dot syntax:
-- @matrix.get :: Thrice (Thrice a)@
-- The latter requires the @OverloadedRecordDot@ language extension,
-- which is enabled at the top of this file.
newtype Matrix a = MkMatrix {get :: Thrice (Thrice a)}


-- | MkMatrix $ \case
--   ...cases...
-- is exactly the same as
-- MkMatrix $ \i ->
--   case i of
--     ...cases...
-- It requires the `LambdaCase` language extension - it's enabled at the top of the file
matrix ::
  a ->
  a ->
  a ->
  a ->
  a ->
  a ->
  a ->
  a ->
  a ->
  Matrix a
matrix x0 x1 x2 y0 y1 y2 z0 z1 z2 =
  MkMatrix $
    thrice
      (thrice x0 x1 x2)
      (thrice y0 y1 y2)
      (thrice z0 z1 z2)

constantMatrix :: a -> Matrix a
constantMatrix x = matrix x x x x x x x x x

diagonalMatrix :: a -> Matrix (Maybe a)
diagonalMatrix x = MkMatrix $ \i j -> if i == j then Just x else Nothing

-- help function for otherDiagonalMatrix
toInt :: Three -> Int
toInt Zero = 0
toInt One  = 1
toInt Two  = 2

otherDiagonalMatrix :: a -> Matrix (Maybe a)
otherDiagonalMatrix x = MkMatrix $ \i j -> if toInt i + toInt j == 2 then Just x else Nothing

addMatrix :: Matrix Integer -> Matrix Integer -> Matrix Integer
addMatrix (MkMatrix x) (MkMatrix y) = MkMatrix $ \i j -> x i j + y i j

showMatrix :: (a -> String) -> Matrix a -> String
showMatrix toString (MkMatrix x) =
  unlines (map (\i -> toString (x i Zero) ++ " " ++
                      toString (x i One) ++ " " ++ 
                      toString (x i Two)) [Zero, One, Two])

ix :: Three -> Three -> Matrix a -> a
ix i j (MkMatrix x) = x i j

getRow :: Three -> Matrix a -> Thrice a
getRow i (MkMatrix x) = thrice (x i Zero) (x i One) (x i Two)

getCol :: Three -> Matrix a -> Thrice a
getCol i (MkMatrix x) = thrice (x Zero i) (x One i) (x Two i)

getDiag :: Matrix a -> Thrice a
getDiag (MkMatrix x) = thrice (x Zero Zero) (x One One) (x Two Two)

getOtherDiag :: Matrix a -> Thrice a
getOtherDiag (MkMatrix x) = thrice (x Zero Two) (x One One) (x Two Zero)

transpose :: Matrix a -> Matrix a
transpose (MkMatrix x) = MkMatrix $ \i j -> x j i

foldThriceWith :: (a -> a -> a) -> Thrice a -> a
foldThriceWith op f = op (f Zero) (op (f One) (f Two))

foldMatrixWith :: (a -> a -> a) -> Matrix a -> a
foldMatrixWith op (MkMatrix x) = 
         foldThriceWith op (getRow Zero (MkMatrix x)) 
    `op` foldThriceWith op (getRow One (MkMatrix x)) 
    `op` foldThriceWith op (getRow Two (MkMatrix x))


eqMatrix :: (a -> a -> Bool) -> Matrix a -> Matrix a -> Bool
eqMatrix eq x y = foldMatrixWith (&&) $ MkMatrix $ \i j -> eq (ix i j x) (ix i j y)

imapThrice :: (Three -> a -> b) -> Thrice a -> Thrice b
imapThrice f t = thrice (f Zero (t Zero)) (f One (t One)) (f Two (t Two))

mapThrice :: (a -> b) -> Thrice a -> Thrice b
mapThrice f t = thrice (f (t Zero)) (f (t One)) (f (t Two))

imapMatrix :: (Three -> Three -> a -> b) -> Matrix a -> Matrix b
imapMatrix f (MkMatrix x) = MkMatrix $ \i j -> f i j (x i j)

mapMatrix :: (a -> b) -> Matrix a -> Matrix b
mapMatrix f (MkMatrix x) = MkMatrix $ \i j -> f (x i j)

place :: Three -> Three -> a -> Matrix a -> Matrix a
place i j x m = imapMatrix (\i' j' _ -> if i' == i && j' == j then x else ix i' j' m) m

concatThriceWith :: String -> Thrice String -> String
concatThriceWith x y = (y Zero) ++ x ++ (y One) ++ x ++ (y Two)

concatMatrixWith :: String -> String -> Matrix String -> String
concatMatrixWith rowS colS (MkMatrix x) = 
    concatThriceWith colS (getRow Zero (MkMatrix x)) ++ rowS ++
    concatThriceWith colS (getRow One (MkMatrix x)) ++ rowS ++
    concatThriceWith colS (getRow Two (MkMatrix x))

showMatrixComposition :: (a -> String) -> Matrix a -> String
showMatrixComposition toString (MkMatrix x) = concatMatrixWith "\n" " " (mapMatrix toString (MkMatrix x))

instance Show a => Show (Matrix a) where
  show = showMatrix show

{-
type GenericMatrix =

foldGenericMatrix ::
mapGenericMatrix ::
multGenericMatrix ::
-}
